Q1. A group of people from different parts of Ranchi visited ‘Universal Studio’, Singapore and they enjoyed various fun events.  
 - The first event was ‘Roller Coaster’ for which the ticket price was 44 dollars for male, 38 dollars for females and 21 dollars for kids. They spent a total of 1412 dollars for this event.
 - Second event was ‘4D Max Cinema’ for which ticket prices were 32 dollars, 28 dollars and 15 dollars respectively. They spent 1024 dollars for this event.
 - Finally they had a ‘cable car’ trip for which the ticket prices were 24 dollars, 20 dollars and 10 dollars respectively. They spent 728 dollars for the cable car trip.  

Determine the number of males, females and kids in the group. (Use numpy)


In [6]:
import numpy as np
a = np.array([
    [44, 38, 21],
    [32, 28, 15],
    [24, 20, 10]
])

b = np.array([
    [1412],
    [1024],
    [728]
])

x = np.dot(np.linalg.inv(a), b)
print(f"No of males: {np.round(x[0, 0])}")
print(f"No of females: {np.round(x[1, 0])}")
print(f"No of kids: {np.round(x[2, 0])}")


No of males: 12.0
No of females: 10.0
No of kids: 24.0


Q2. Write a python script to 
Construct two numpy 3D arrays A1 and A2 of any shape set by the user at run time and the elements are randomly generated by the system. Perform the following steps 
 - Construct an array by selecting all the elements of the first array (A1) that are divisible by 5 
 - Construct another array by selecting all the elements of the second array (A2) that are divisible by 4  
 - Join 1 and 2 to form a single dimensional array and construct the largest possible square matrix from it 


In [ ]:
import numpy as np

shapea1 = tuple(list(int(i) for i in input("Enter shape of matrix A1: ").split()))
shapea2 = tuple(list(int(i) for i in input("Enter shape of matrix A2: ").split()))

A1 = np.empty(shapea1)
A2 = np.empty(shapea2)

for layer in A1:
    for row in layer:
        for idx, element in enumerate(row):
            row[idx] = np.random.randint(0, 1000)
for layer in A2:
    for row in layer:
        for idx, element in enumerate(row):
            row[idx] = np.random.randint(0, 1000)

A1flat = A1.flatten()
A1div5 = A1flat[A1flat % 5 == 0]

A2flat = A2.flatten()
A2div4 = A2flat[A2flat % 4 == 0]

combined = np.concatenate((A1div5, A2div4))
if(len(combined) ** (1/2) == int(len(combined) ** (1/2))):
    sqmat = combined.reshape((int(len(combined) ** (1/2)), int(len(combined) ** (1/2))))
else:
    print("Length of combined matrices cannot be formed into a square.")

print(sqmat)

[[ 10.  75. 908.]
 [628. 216. 600.]
 [832.   8. 100.]]


Q3. Define a function `Create_Array()` that can create an array of flexible size according to the number of arguments passed within the function call. The elements passed in the function should make the diagonal Elements of the array and the rest of the elements can be all zeros
For Example, if the function call is Create_Array(1,2,3,4)  
The function shall return  
1 0 0 0  
0 2 0 0  
0 0 3 0  
0 0 0 4  


In [34]:
import numpy as np

def Create_Array(*args):
    mat = np.zeros((len(args), len(args)))
    for i in range(len(args)):
        mat[i, i] = args[i]

    return mat

print(Create_Array(1, 2, 3, 4))

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
